baseURL = "http://ContinuousIsolation.com/"
languageCode = "en-us"
title = "Continuous Isolation"

theme = "docdock"

[params]
editURL = "https://github.com/paul-hammant/ci/edit/master/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/paul-hammant/ci"
weight = 10
